### ISSUE TITLE
Исправление AliExpress 

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [grandsilence/pixelperfect-fonts#1]
.

**Comment by grandsilence** [comment]
@userskill замена шрифта Aliexpress на Arial для читаемости без сглаживания. Ставить, подключив CSS файл в браузере Cent Browser, Chrome сторонних CSS поддержки не имеет.

**Comment by userskill** [comment]
а как там много файлов? и еще я просто cente поставил 
### *
{
font-family: tahoma !important;
}
*

**Comment by grandsilence** [comment]
@userskill Не совсем понял что вы имеете ввиду. Файл там только один, с расширением `.css`.
